version: 2

references:
  dotnet_image: &dotnet_image
    docker:
    - image: fsharp:netcore

  attach_workspace: &attach_workspace
    attach_workspace:
      at: .

  master_branch: &master_branch
    filters:
      branches:
        only:
        - master

jobs:
  setup:
    <<: *dotnet_image
    steps:
    - checkout
    - persist_to_workspace:
        root: .
        paths:
        - .
        - src

  test-and-build:
    <<: *dotnet_image
    steps:
    - *attach_workspace
    - run: apt-get update
    - run: apt-get --no-install-recommends install -y make
    - run: make build-test
    - run: make build-package
    - persist_to_workspace:
        root: .
        paths:
          - src

  publish-to-bintray:
    <<: *dotnet_image
    steps:
    - *attach_workspace
    - run: apt-get update
    - run: apt-get --no-install-recommends install -y make
    - run: make publish

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - setup

    - test-and-build:
        requires:
        - setup

    - approve-publish:
        type: approval
        requires:
        - test-and-build

    - publish-to-bintray:
        requires:
        - approve-publish
