version: 2

references:
  dotnet_image: &dotnet_image
    docker:
    - image: fsharp:netcore

  attach_workspace: &attach_workspace
    attach_workspace:
      at: .

  master_branch: &master_branch
    filters:
      branches:
        only:
        - master

jobs:
  setup:
    <<: *dotnet_image
    steps:
    - checkout
    - persist_to_workspace:
        root: .
        paths:
        - .
        - gradle
        - src

  test-and-build:
    <<: *dotnet_image
    steps:
    - *attach_workspace
    - run:
        name: build & test
        command: make build-test

  publish-to-bintray:
    <<: *dotnet_image
    steps:
    - *attach_workspace
    - run:
        name: publish to bintray
        command: make publish

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - setup

    - test-and-build:
        requires:
        - setup

    - approve-publish:
        <<: *master_branch
        type: approval
        requires:
        - test-and-build

    - publish-to-bintray:
        <<: *master_branch
        requires:
        - approve-publish
